name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Du æ jaggu mæ bæst! Vi ska fiks herre 7.'
        pr-message: 'Nydelig PR! flyrev hadde aldri godkjent den.'
